server:
     port: 12345
     path: /hello

#person:
#     lastName: zhangsan
#     age: 18
#     boss: true
#     birth: 2018/11/11  #默认的日期格式是这种
#     maps: {k1: v1,k2: v2}
#     lists:
#        - lisi
#        - wangwu
#     dog:
#       name: 小狗
#       age: 2

